import java.math.BigInteger;

/*
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *  By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	
	By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	 find the sum of the even-valued terms.
 */
public class evenFibonacciNumbers {
	
	public static void main(String[] args){
		long sum = 0,p1=1,p2=2,evenSum=2;
		
		while(sum<4000000){
			sum=p1+p2;
			p1=p2;
			p2=sum;

			if(sum%2==0){
				evenSum=evenSum+sum;
			}
			
		}
		System.out.println("The total sum of even numbers in the Fibonacci sequence lower than 4,000,000 is: "+evenSum);
	}

}
